# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: GoVulnCheck

on: [push]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - uses: actions/checkout@v3

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.21
           go-package: ./...
